[package]
name = "tjpp"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
current_platform = "0.2.0"
rand = "0.9.1"
sdl3 = { version = "0", features = [] }
serde = "1.0.219"
serde_json = "1.0.140"
