name: Build

on: push

jobs:
  build:
    strategy:
      matrix:
        BUILD_TARGET: [release]
        os: [ubuntu-24.04, ubuntu-24.04-arm, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: extractions/setup-just@v2
        with:
          just-version: 1.40.0
      - uses: actions/checkout@v4

      - name: Check just works
        run: just

      - name: Create build folder
        run: |
          mkdir builds
          mkdir builds/${{RUNNER_OS}}

      - name: Install required dependencies
        run: |

      - name: Install
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
               sudo apt-get update
               sudo apt-get install libjpeg-dev libwebp-dev libtiff5-dev libsdl2-image-dev libsdl2-image-2.0-0 -y
          elif [ "$RUNNER_OS" == "Windows" ]; then
               vcpkg install sdl2 sdl2-image
          else
               echo "$RUNNER_OS not supported"
               exit 1
          fi
        shell: bash

      - name: Build ${{RUNNER_OS}}
        run: |
          cargo clean
          just build
          cp target/release/tjpp builds/${{RUNNER_OS}}
          cp -r assets builds/${{RUNNER_OS}}
      - name: Upload ${{RUNNER_OS}}
        uses: actions/upload-artifact@v4
        with:
          name: tjpp-${{RUNNER_OS}}
          path: |
            builds/${{RUNNER_OS}}
