name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]
    steps:
      - uses: extractions/setup-just@v2
        with:
          just-version: 1.40.0
      - uses: actions/checkout@v4
      - name: Check just works
        run: just
      - name: Install cross.rs
        run: just install_cross
      - name: Build linux x86_64 with just
        run: just build
      - name: Build linux aarch64 with just
        run: just linux_aarch64
      # - name: Build windows x86_64 with just
      #   run: just cc_windows # use cc_windows cuz cross fails on windows for some reason
      - name: Upload linux-x86_64
        uses: actions/upload-artifact@v4
        with:
          name: tjpp-linux-x86_64
          path: |
            target/release/tjpp
      - name: Upload linux-x86_64
        uses: actions/upload-artifact@v4
        with:
          name: tjpp-linux-aarch64
          path: |
            target/aarch64-unknown-linux-gnu/release/tjpp
      # - name: Upload windows-x86_64
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: tjpp-windows-x86_64.exe
      #     path: |
      #       target/x86_64-pc-windows-gnu/release/tjpp.exe
