name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]
    steps:
      - uses: actions/checkout@v4
      - name: Install just
        run: mkdir -p ~/bin; curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --tag 1.40.0 --to ~/bin; export PATH="$PATH:$HOME/bin"
      - name: Check just works
        run: just
      - name: Install cross.rs
        run: just install_cross
      - name: Build linux x86_64 with just
        run: just build
      - name: Build windows x86_64 with just
        run: just windows
