name: Build

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v2
        with:
          just-version: 1.40.0
      - uses: actions/checkout@v4
      - name: "Install required dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install libjpeg-dev libwebp-dev libtiff5-dev libsdl2-image-dev libsdl2-image-2.0-0 -y
      - name: Check just works
        run: just
      - name: Build ${{runner.os}}-${{runner.arch}}
        run: |
          cargo test
  build:
    strategy:
      matrix:
        BUILD_TARGET: [release]
        # os: [windows-latest, windows-11-arm]
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: extractions/setup-just@v2
        with:
          just-version: 1.40.0
      - uses: actions/checkout@v4

      - name: Check just works
        run: just

      - name: Create build folder
        run: |
          mkdir builds
          mkdir builds/${{runner.os}}-${{runner.arch}}

      - name: "Install required dependencies (linux)"
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libjpeg-dev libwebp-dev libtiff5-dev libsdl2-image-dev libsdl2-image-2.0-0 -y

      - name: "Install required dependencies (macos)"
        if: runner.os == 'Macos'
        run: |
          brew install sdl2 sdl2_image
          export LIBRARY_PATH="$LIBRARY_PATH:$(brew --prefix)/lib"

      - name: "Install required dependencies (windows)"
        if: runner.os == 'Windows'
        run: |
          vcpkg install sdl2 sdl2-image
          # below is environment values that rust-sdl2 tells me to set :)
          SET PATH=%PATH%;C:\Users\my_user\dev\vcpkg\installed\x64-windows\bin
          SET INCLUDE=%INCLUDE%;C:\Users\my_user\dev\vcpkg\installed\x64-windows\include
          SET LIB=%LIB%;C:\Users\my_user\dev\vcpkg\installed\x64-windows\lib

      - name: Build ${{runner.os}}-${{runner.arch}}
        run: |
          cargo clean
          just build
          cp target/release/tjpp builds/${{runner.os}}-${{runner.arch}}
          cp -r assets builds/${{runner.os}}-${{runner.arch}}
      - name: Upload ${{runner.os}}-${{runner.arch}}
        uses: actions/upload-artifact@v4
        with:
          name: tjpp-${{runner.os}}-${{runner.arch}}
          path: |
            builds/${{runner.os}}-${{runner.arch}}
