name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]
    steps:
      - uses: extractions/setup-just@v2
        with:
          just-version: 1.40.0
      - uses: actions/checkout@v4
      - name: Check just works
        run: just
      - name: Install cross.rs
        run: just install_cross
      - name: Clean building environment
        run: cargo clean

      ## we can only feasibly build linux (x86_64 & aarch64) and windows (x86_64 only)
      # this is because macos has licensing issues, and aarch64 windows doesn't have a gnu toolchain (msvc has licensing issues too)
      # i think i'll have to manually build these targets, but i can only do macos aarch64, which should be fine

      # linux x86_64
      - name: Build linux x86_64 with just
        run: just build
      - name: Upload linux-x86_64
        uses: actions/upload-artifact@v4
        with:
          name: tjpp-linux-x86_64
          path: |
            target/release/tjpp

      # linux aarch64
      - name: Clean building environment
        run: cargo clean
      - name: Build linux aarch64 with just
        run: just linux_aarch64
      - name: Upload linux-aarch64
        uses: actions/upload-artifact@v4
        with:
          name: tjpp-linux-aarch64
          path: |
            target/aarch64-unknown-linux-gnu/release/tjpp

      # windows x86_64
      - name: Clean building environment
        run: cargo clean
      - name: Build windows x86_64 with just
        run: just windows
      - name: Upload windows-x86_64
        uses: actions/upload-artifact@v4
        with:
          name: tjpp-windows-x86_64.exe
          path: |
            target/x86_64-pc-windows-gnu/release/tjpp.exe
