name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]
    steps:
      - uses: actions/checkout@v4
      - name: Install required packages
        run: sudo apt install just
      - name: Check just works
        run: just
      - name: Install cross.rs
        run: just install_cross
      - name: Build linux x86_64 with just
        run: just build
      - name: Build windows x86_64 with just
        run: just windows
