name: Build

on: push

jobs:
  build:
    strategy:
      matrix:
        BUILD_TARGET: [release]
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: extractions/setup-just@v2
        with:
          just-version: 1.40.0
      - uses: actions/checkout@v4

      - name: Check just works
        run: just

      - name: Create build folder
        run: |
          mkdir builds
          mkdir builds/${{ matrix.os }}

      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libjpeg-dev libwebp-dev libtiff5-dev libsdl2-image-dev libsdl2-image-2.0-0 -y

      - name: Build ${{ matrix.os }}
        run: |
          cargo clean
          just build
          cp target/release/tjpp builds/${{ matrix.os }}
          cp -r assets builds/${{ matrix.os }}
      - name: Upload ${{ matrix.os }}
        uses: actions/upload-artifact@v4
        with:
          name: tjpp-${{ matrix.os }}
          path: |
            builds/${{ matrix.os }}
