name: Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]
    steps:
      - uses: extractions/setup-just@v2
        with:
          just-version: 1.40.0
      - uses: actions/checkout@v4

      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libjpeg-dev libwebp-dev libtiff5-dev libsdl2-image-dev libsdl2-image-2.0-0 -y

      - name: Check just works
        run: just

      - name: Check that cargo works
        run: cargo

      - name: Run cargo tests
        run: cargo test --verbose

      - name: Run clippy tests
        run: cargo clippy --all-targets --all-features
